### ISSUE TITLE
Change ESP32RGPPanel settings for 8048S3043 board

### ISSUE THREAD

**Issue by nfigueir** [eCrowneEng/ESP-SimHub-ESP32S3-SCREEN#1]
Hi,

First of all thank you for your work in setting this up. I bought a 4.3 800x480 board to play with SimHub dashboard and I was having some issues getting your example to work as I was only getting a white screen.

After some search I was able to get it working by changing the definition of  Arduino_ESP32RGBPanel to the following:

Arduino_ESP32RGBPanel *rgbpanel = new Arduino_ESP32RGBPanel(
    40 /* DE */, 41 /* VSYNC */, 39 /* HSYNC */, 42 /* PCLK */,
    45 /* R0 */, 48 /* R1 */, 47 /* R2 */, 21 /* R3 */, 14 /* R4 */,
    5 /* G0 */, 6 /* G1 */, 7 /* G2 */, 15 /* G3 */, 16 /* G4 */, 4 /* G5 */,
    8 /* B0 */, 3 /* B1 */, 46 /* B2 */, 9 /* B3 */, 1 /* B4 */,
    0 /* hsync_polarity */, 8 /* hsync_front_porch */, 4 /* hsync_pulse_width */, 16 /* hsync_back_porch */,
    0 /* vsync_polarity */, 4 /* vsync_front_porch */, 4 /* vsync_pulse_width */, 4 /* vsync_back_porch */,
    1 /* pclk_active_neg */, 16000000 /* prefer_speed */
);
You may want to include this as an option.

**Comment by ecoreng** [comment]
can you link the actual screen pls?

**Comment by nfigueir** [comment]
Here you go:
DIYmalls 4.3" inch ESP32 Display ILI9485 IPS TFT LCD Module
ESP32-8048S043C-I Capacitive Touch Screen 800x480 ESP32-S3-WROOM-1
Development Board for Arduino IDE https://a.co/d/7Nxq3Sy

**Comment by ecoreng** [comment]
done:
https://github.com/eCrowneEng/ESP-SimHub-ESP32S3-SCREEN/commit/b7dc3eb4189a14decbded7a4298ecbd0deec3985

thanks for reporting
